USE supermercado;

DROP TABLE IF EXISTS Cliente;
DROP TABLE IF EXISTS Endereco;

CREATE TABLE Endereco (
    Endereco_ID INT AUTO_INCREMENT PRIMARY KEY,
    Rua VARCHAR(255) NOT NULL,
    CEP VARCHAR(20) NOT NULL
);

CREATE TABLE Cliente (
    Cliente_ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Endereco_ID INT NOT NULL,
    FOREIGN KEY (Endereco_ID) REFERENCES Endereco(Endereco_ID) ON DELETE CASCADE
);